// mrext
// Copyright (c) 2026 mrext contributors.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of mrext.
//
// mrext is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// mrext is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with mrext. If not, see <http://www.gnu.org/licenses/>.

package main

import (
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/wizzomafizzo/mrext/pkg/games"
	"github.com/wizzomafizzo/mrext/pkg/utils"
)

func main() {
	systems := make([]games.System, 0, len(games.Systems))
	for id := range games.Systems {
		systems = append(systems, games.Systems[id])
	}
	sort.Slice(systems, func(i, j int) bool {
		return systems[i].Name < systems[j].Name
	})

	var document strings.Builder
	_, _ = document.WriteString("<!--- This file is automatically generated. Do not edit. --->\n\n")
	_, _ = document.WriteString("# Systems\n\n")
	_, _ = document.WriteString(
		"This is a list of all systems supported by the MiSTer Extensions scripts. " +
			"Please [open an issue](https://github.com/wizzomafizzo/mrext/issues/new) " +
			"if a system is missing or not working.\n\n",
	)

	var tocConsole []string
	var tocComputer []string
	var tocOther []string
	for i := range systems {
		system := &systems[i]
		tocAnchor := "#" + strings.ReplaceAll(strings.ToLower(system.Name), " ", "-")
		tocAnchor = utils.StripChars(tocAnchor, "()/")
		tocLink := fmt.Sprintf("[%s](%s)", system.Name, tocAnchor)
		switch {
		case strings.HasPrefix(system.Rbf, "_Console"):
			tocConsole = append(tocConsole, tocLink)
		case strings.HasPrefix(system.Rbf, "_Computer"):
			tocComputer = append(tocComputer, tocLink)
		default:
			tocOther = append(tocOther, tocLink)
		}
	}

	_, _ = fmt.Fprintf(&document, "**Consoles:** %s\n\n\n", strings.Join(tocConsole, ", "))
	_, _ = fmt.Fprintf(&document, "**Computers:** %s\n\n\n", strings.Join(tocComputer, ", "))
	_, _ = fmt.Fprintf(&document, "**Other:** %s\n\n\n", strings.Join(tocOther, ", "))

	_, _ = document.WriteString("## Core Groups\n")
	_, _ = document.WriteString(
		"Core groups are aliases to multiple systems. They work as system IDs for all configuration options " +
			"where a user must type a system ID manually. MiSTer Extensions differentiates between systems " +
			"more than MiSTer itself, and these are included as a convenience so system folder names can still " +
			"be used as IDs.\n\n",
	)
	_, _ = document.WriteString("| ID | Systems |\n| --- | --- |\n")
	groups := utils.MapKeys(games.CoreGroups)
	sort.Strings(groups)
	for _, id := range groups {
		groupSystems := games.CoreGroups[id]
		members := make([]string, 0, len(groupSystems))
		for i := range groupSystems {
			system := &groupSystems[i]
			anchor := "#" + strings.ReplaceAll(strings.ToLower(system.Name), " ", "-")
			members = append(members, fmt.Sprintf("[%s](%s)", system.Name, anchor))
		}
		_, _ = fmt.Fprintf(&document, "| %s | %s |\n", id, strings.Join(members, ", "))
	}

	for i := range systems {
		system := &systems[i]
		_, _ = fmt.Fprintf(&document, "\n## %s\n", system.Name)
		info := []string{fmt.Sprintf("**ID**: %s ", system.Id)}
		if len(system.Alias) > 0 {
			info = append(info, fmt.Sprintf("**Aliases**: %s ", strings.Join(system.Alias, ", ")))
		}
		info = append(info, "**Folders**: "+strings.Join(system.Folder, ", "))
		rbf := "**RBF**:"
		if system.Rbf != "" {
			rbf += " " + system.Rbf
		}
		info = append(info, rbf)
		_, _ = fmt.Fprintf(&document, "\n%s\n\n", strings.Join(info, " | "))

		if len(system.Slots) > 0 {
			_, _ = document.WriteString(
				"\n| Label | Files | Delay | Type | Index |\n| --- | --- | --- | --- | --- |\n",
			)
			for _, slot := range system.Slots {
				files := "-"
				if len(slot.Exts) > 0 {
					files = strings.Join(slot.Exts, ", ")
				}
				label := "-"
				delay := "-"
				fileType := "-"
				index := "-"
				if slot.Label != "" {
					label = slot.Label
				}
				if slot.Mgl != nil {
					delay = strconv.Itoa(slot.Mgl.Delay)
					fileType = slot.Mgl.Method
					index = strconv.Itoa(slot.Mgl.Index)
				}
				_, _ = fmt.Fprintf(
					&document,
					"| %s | %s | %s | %s | %s |\n",
					label,
					files,
					delay,
					fileType,
					index,
				)
			}
		}
		_, _ = document.WriteString("\n[Back to top](#systems)\n")
	}

	// #nosec G306 -- generated documentation must remain world-readable.
	if err := os.WriteFile("docs/systems.md", []byte(document.String()), 0o644); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
