package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/wizzomafizzo/mrext/pkg/games"
	"github.com/wizzomafizzo/mrext/pkg/utils"
)

func main() {
	var systems []games.System
	for _, system := range games.Systems {
		systems = append(systems, system)
	}
	sort.Slice(systems, func(i, j int) bool {
		return systems[i].Name < systems[j].Name
	})

	var document strings.Builder
	document.WriteString("<!--- This file is automatically generated. Do not edit. --->\n\n")
	document.WriteString("# Systems\n\n")
	document.WriteString("This is a list of all systems supported by the MiSTer Extensions scripts. Please [open an issue](https://github.com/wizzomafizzo/mrext/issues/new) if a system is missing or not working.\n\n")

	var tocConsole []string
	var tocComputer []string
	var tocOther []string
	for _, system := range systems {
		tocAnchor := "#" + strings.ReplaceAll(strings.ToLower(system.Name), " ", "-")
		tocAnchor = utils.StripChars(tocAnchor, "()/")
		tocLink := fmt.Sprintf("[%s](%s)", system.Name, tocAnchor)
		switch {
		case strings.HasPrefix(system.Rbf, "_Console"):
			tocConsole = append(tocConsole, tocLink)
		case strings.HasPrefix(system.Rbf, "_Computer"):
			tocComputer = append(tocComputer, tocLink)
		default:
			tocOther = append(tocOther, tocLink)
		}
	}

	fmt.Fprintf(&document, "**Consoles:** %s\n\n\n", strings.Join(tocConsole, ", "))
	fmt.Fprintf(&document, "**Computers:** %s\n\n\n", strings.Join(tocComputer, ", "))
	fmt.Fprintf(&document, "**Other:** %s\n\n\n", strings.Join(tocOther, ", "))

	document.WriteString("## Core Groups\n")
	document.WriteString("Core groups are aliases to multiple systems. They work as system IDs for all configuration options where a user must type a system ID manually. MiSTer Extensions differentiates between systems more than MiSTer itself, and these are included as a convenience so system folder names can still be used as IDs.\n\n")
	document.WriteString("| ID | Systems |\n| --- | --- |\n")
	groups := utils.MapKeys(games.CoreGroups)
	sort.Strings(groups)
	for _, id := range groups {
		var members []string
		for _, system := range games.CoreGroups[id] {
			anchor := "#" + strings.ReplaceAll(strings.ToLower(system.Name), " ", "-")
			members = append(members, fmt.Sprintf("[%s](%s)", system.Name, anchor))
		}
		fmt.Fprintf(&document, "| %s | %s |\n", id, strings.Join(members, ", "))
	}

	for _, system := range systems {
		fmt.Fprintf(&document, "\n## %s\n", system.Name)
		info := []string{fmt.Sprintf("**ID**: %s ", system.Id)}
		if len(system.Alias) > 0 {
			info = append(info, fmt.Sprintf("**Aliases**: %s ", strings.Join(system.Alias, ", ")))
		}
		info = append(info, fmt.Sprintf("**Folders**: %s", strings.Join(system.Folder, ", ")))
		rbf := "**RBF**:"
		if system.Rbf != "" {
			rbf += " " + system.Rbf
		}
		info = append(info, rbf)
		fmt.Fprintf(&document, "\n%s\n\n", strings.Join(info, " | "))

		if len(system.Slots) > 0 {
			document.WriteString("\n| Label | Files | Delay | Type | Index |\n| --- | --- | --- | --- | --- |\n")
			for _, slot := range system.Slots {
				files := "-"
				if len(slot.Exts) > 0 {
					files = strings.Join(slot.Exts, ", ")
				}
				label := "-"
				delay := "-"
				fileType := "-"
				index := "-"
				if slot.Label != "" {
					label = slot.Label
				}
				if slot.Mgl != nil {
					delay = fmt.Sprintf("%d", slot.Mgl.Delay)
					fileType = slot.Mgl.Method
					index = fmt.Sprintf("%d", slot.Mgl.Index)
				}
				fmt.Fprintf(&document, "| %s | %s | %s | %s | %s |\n", label, files, delay, fileType, index)
			}
		}
		document.WriteString("\n[Back to top](#systems)\n")
	}

	if err := os.WriteFile("docs/systems.md", []byte(document.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
