name: Repo database creation
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release"]
    types: [completed]

permissions:
  contents: write

jobs:
  mrext-repo:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    env:
      DB_ID: mrext/all
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - name: Get latest mrext release
        id: mrextreleaseinfo
        uses: cardinalby/git-get-release-action@v1
        with:
          latest: true
          repo: wizzomafizzo/mrext
          ref: main
      - name: Download release files
        run: |
          DL_URL=https://github.com/wizzomafizzo/mrext/releases/download/${{ steps.mrextreleaseinfo.outputs.tag_name }}
          mkdir -p _bin/releases
          for file in lastplayed.sh launchsync.sh playlog.sh random.sh remote.sh search.sh; do
            curl -fsSL "$DL_URL/$file" -o "_bin/releases/$file"
          done
      - name: Update external scripts
        run: go run github.com/magefile/mage updateExternalApps
      - name: Create databases
        run: |
          cp scripts/generate_repo.py .
          python generate_repo.py ${{ steps.mrextreleaseinfo.outputs.tag_name }}
      - name: Commit databases
        uses: EndBug/add-and-commit@v9
        with:
          add: releases/* -f -A
